#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

terminator()
{
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done

101-manage_my_process

#!/usr/bin/env bash
#Manages the script manage_my_process.

if [ "$1" == "start" ]
then
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
	kill "$(pgrep -f ./manage_my_process)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
	kill "$(pgrep -f ./manage_my_process)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"

else
	echo  "Usage: manage_my_process {start|stop|restart}"
fi

