#!/usr/bin/env bash
# This script displays the time from 0 to 12 hours and 1 to 59 minutes.

hour=0

# Use a while loop to display hours from 0 to 12
while [ $hour -le 12 ]; do
    minute=1

    # Use a nested while loop to display minutes from 1 to 59
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
    done

    ((hour++))
done

